<option value="AU">Австралія</option>
              <option value="AT">Австрія</option>
              <option value="AZ">Азербайджан</option>
              <option value="AX">Аландські острови</option>
              <option value="AL">Албанія</option>
              <option value="DZ">Алжир</option>
              <option value="AS">Американське Самоа</option>
              <option value="VI">Американські Віргінські Острови</option>
              <option value="AI">Ангілья</option>
              <option value="AO">Ангола</option>
              <option value="AD">Андорра</option>
              <option value="AQ">Антарктида</option>
              <option value="AG">Антигуа і Барбуда</option>
              <option value="AR">Аргентина</option>
              <option value="AW">Аруба</option>
              <option value="AF">Афганістан</option>
              <option value="BS">Багамські Острови</option>
              <option value="BD">Бангладеш</option>
              <option value="BB">Барбадос</option>
              <option value="BH">Бахрейн</option>
              <option value="BZ">Беліз</option>
              <option value="BE">Бельгія</option>
              <option value="BJ">Бенін</option>
              <option value="BM">Бермудські Острови</option>
              <option value="BY">Білорусь</option>
              <option value="BG">Болгарія</option>
              <option value="BO">Болівія</option>
              <option value="BA">Боснія і Герцеговина</option>
              <option value="BW">Ботсвана</option>
              <option value="BR">Бразилія</option>
              <option value="IO">Британська Територія в Індійському Океані</option>
              <option value="VG">Британські Віргінські Острови</option>
              <option value="BN">Бруней</option>
              <option value="BF">Буркіна-Фасо</option>
              <option value="BI">Бурунді</option>
              <option value="BT">Бутан</option>
              <option value="VU">Вануату</option>
              <option value="VA">Ватикан</option>
              <option value="GB">Велика Британія</option>
              <option value="VE">Венесуела</option>
              <option value="VN">В'єтнам</option>
              <option value="AM">Вірменія</option>
              <option value="WF">Волліс і Футуна</option>
              <option value="GA">Габон</option>
              <option value="HT">Гаїті</option>
              <option value="GY">Гаяна</option>
              <option value="GM">Гамбія</option>
              <option value="GH">Гана</option>
              <option value="GP">Гваделупа</option>
              <option value="GT">Гватемала</option>
              <option value="GN">Гвінея</option>
              <option value="GW">Гвінея-Бісау</option>
              <option value="GG">Гернсі</option>
              <option value="HN">Гондурас</option>
              <option value="HK">Гонконг</option>
              <option value="GD">Гренада</option>
              <option value="GR">Греція</option>
              <option value="GE">Грузія</option>
              <option value="GU">Гуам</option>
              <option value="GI">Гібралтар</option>
              <option value="GL"> Ґренландія</option>
              <option value="DK">Данія</option>
              <option value="CD">ДР Конго</option>
              <option value="JE">Джерсі</option>
              <option value="DJ">Джибуті</option>
              <option value="DM"> Домініка</option>
              <option value="DO">Домініканська Республіка</option>
              <option value="UM">Зовнішні малі острови США</option>
              <option value="EC">Еквадор</option>
              <option value="GQ">Екваторіальна Гвінея </option>
              <option value="ER">Еритрея</option>
              <option value="EE">Естонія</option>
              <option value="ET">Ефіопія</option>
              <option value="EG">Єгипет</option>
              <option value="YE">Ємен</option>
              <option value="ZM">Замбія</option>
              <option value="EH">Західна Сахара</option>
              <option value="ZW">Зімбабве</option>
              <option value="IL">Ізраїль</option>
              <option value="IN">Індія</option>
              <option value="ID">Індонезія</option>
              <option value="IQ">Ірак</option>
              <option value="IR">Іран</option>
              <option value="IE">Ірландія</option>
              <option value="IS">Ісландія</option>
              <option value="ES">Іспанія</option>
              <option value="IT">Італія</option>
              <option value="JO">Йорданія</option>
              <option value="CV">Кабо-Верде</option>
              <option value="KZ">Казахстан</option>
              <option value="KY">Кайманові Острови</option>
              <option value="KH">Камбоджа</option>
              <option value="CM">Камерун</option>
              <option value="CA">Канада</option>
              <option value="QA">Катар</option>
              <option value="KE">Кенія</option>
              <option value="KG">Киргизстан</option>
              <option value="CN">КНР</option>
              <option value="CY">Кіпр</option>
              <option value="KI">Кірибаті</option>
              <option value="CC">Кокосові острови</option>
              <option value="CO">Колумбія</option>
              <option value="KM">Коморські Острови</option>
              <option value="CG">Республіка Конго</option>
              <option value="CR">Коста-Рика</option>
              <option value="CI">Кот-д'Івуар</option>
              <option value="CU">Куба</option>
              <option value="KW">Кувейт</option>
              <option value="CW">Кюрасао</option>
              <option value="LA">Лаос</option>
              <option value="LV">Латвія</option>
              <option value="LS">Лесото</option>
              <option value="LT">Литва</option>
              <option value="LR">Ліберія </option>
              <option value="LB">Ліван</option>
              <option value="LY">Лівія</option>
              <option value="LI">Ліхтенштейн</option>
              <option value="LU">Люксембург</option>
              <option value="MU">Маврикій</option>
              <option value="MR">Мавританія</option>
              <option value="MG">Мадагаскар</option>
              <option value="YT">Майотта</option>

              <option value="MY"> Малайзія</option>

              <option value="MV"> Мальдіви</option>
              <option value="MT">Мальта</option>

              <option value="MX">Мексика</option>

              <option value="MD">Молдова</option>

              <option value="DE">Німеччина</option>
              <option value="NZ">Нова Зеландія</option>
              <option value="NO">Норвегія</option>
              <option value="AE">ОАЕ</option>
              <option value="OM">Оман</option>
              <option value="PL">Польща</option>
              <option value="PT">Португалія</option>
              <option value="SA">Саудівська Аравія</option>
              <option value="SC">Сейшельські Острови</option>
              <option value="RS">Сербія</option>
              <option value="SY">Сирія</option>
              <option value="SG">Сінгапур</option>
              <option value="SK">Словаччина</option>
              <option value="SB">Соломонові Острови</option>
              <option value="SO">Сомалі</option>
              <option value="US">США</option>
              <option value="TL">Східний Тимор</option>
              <option value="TH">Таїланд</option>
              <option value="TW">Тайвань</option>
              <option value="HU">Угорщина</option>
              <option value="FR"> Франція</option>
              <option value="HR">Хорватія</option>
              <option value="CZ"> Чехія</option>
              <option value="CL">Чилі</option>
              <option value="ME">Чорногорія</option>
              <option value="CH">Швейцарія</option>
              <option value="SE">Швеція</option>
              <option value="LK">Шрі-Ланка</option>
              <option value="JM">Ямайка</option>
              <option value="JP">Японія</option>